Jagger: ExampleJLoadScenarioProvider.myFirstJaggerLoadScenario
JLoadScenario ExampleJLoadScenarioProvider.myFirstJaggerLoadScenario ()
Definition at line 127 of file ExampleJLoadScenarioProvider.java.
References com.griddynamics.jagger.user.test.configurations.JTestDefinition.Builder.addValidators(), com.griddynamics.jagger.user.test.configurations.load.JLoadProfileRps.Builder.build(), com.griddynamics.jagger.user.test.configurations.JTestDefinition.Builder.build(), com.griddynamics.jagger.user.test.configurations.JParallelTestsGroup.builder(), com.griddynamics.jagger.user.test.configurations.JLoadScenario.builder(), com.griddynamics.jagger.user.test.configurations.load.JLoadProfileRps.builder(), com.griddynamics.jagger.user.test.configurations.JLoadTest.builder(), com.griddynamics.jagger.user.test.configurations.JTestDefinition.builder(), com.griddynamics.jagger.user.test.configurations.termination.JTerminationCriteriaBackground.getInstance(), com.griddynamics.jagger.user.test.configurations.termination.auxiliary.MaxDurationInSeconds.of(), com.griddynamics.jagger.user.test.configurations.termination.auxiliary.IterationsNumber.of(), com.griddynamics.jagger.user.test.configurations.auxiliary.Id.of(), com.griddynamics.jagger.user.test.configurations.load.auxiliary.RequestsPerSecond.of(), com.griddynamics.jagger.engine.e1.collector.DefaultResponseValidatorProvider.of(), com.griddynamics.jagger.user.test.configurations.termination.JTerminationCriteriaIterations.of(), com.griddynamics.jagger.user.test.configurations.JTestDefinition.Builder.withQueryProvider(), and com.griddynamics.jagger.user.test.configurations.load.JLoadProfileRps.Builder.withWarmUpTimeInMilliseconds().
{
         JTestDefinition description = JTestDefinition
                 .builder(Id.of("myFirstJaggerTestDefinition"), new ExampleEndpointsProvider())
                 // optional
                 .withComment("no comments")
                 .withQueryProvider(new ExampleQueriesProvider())
                 .addValidators(singletonList(DefaultResponseValidatorProvider.of(NotNullResponseValidator.class)))
                 .build();
         JLoadProfile load = JLoadProfileRps.builder(RequestsPerSecond.of(10)).withMaxLoadThreads(10).withWarmUpTimeInMilliseconds(10000).build();
         JLoadProfile load2 = JLoadProfileRps.builder(RequestsPerSecond.of(20)).withMaxLoadThreads(20).withWarmUpTimeInMilliseconds(20000).build();
         JTerminationCriteria termination = JTerminationCriteriaIterations.of(IterationsNumber.of(500), MaxDurationInSeconds.of(60));
         JTerminationCriteria terminationBackground = JTerminationCriteriaBackground.getInstance();
         JLoadTest test1 = JLoadTest.builder(Id.of("my_first_test"), description, load, termination).build();
         JLoadTest test2 = JLoadTest.builder(Id.of("yet_another_test"), description, load2, terminationBackground).build();
         JParallelTestsGroup testGroup = JParallelTestsGroup.builder(Id.of("my_first_test_group"), test1, test2).build();
         return JLoadScenario.builder(Id.of("myFirstJaggerLoadScenario"), testGroup).build();
     }