Jagger: com.griddynamics.jagger.engine.e1.services.DefaultDataService.getMetricsByTestIds
Map<Long, Set<MetricEntity> > com.griddynamics.jagger.engine.e1.services.DefaultDataService.getMetricsByTestIds (Collection< Long > testIds)
Returns map, where key is test id and value is a list of all test metrics.
Parameters
testIds - test ids
Returns
map of <test id, list of metric entity> pairs
Author
Gribov Kirill
Implements com.griddynamics.jagger.engine.e1.services.DataService.
Definition at line 250 of file DefaultDataService.java.
References com.griddynamics.jagger.engine.e1.services.data.service.MetricEntity.setMetricNameDto(), com.griddynamics.jagger.engine.e1.services.data.service.MetricEntity.setPlotAvailable(), and com.griddynamics.jagger.engine.e1.services.data.service.MetricEntity.setSummaryAvailable().
Referenced by com.griddynamics.jagger.engine.e1.services.DefaultDataService.getMetrics(), and com.griddynamics.jagger.engine.e1.services.DefaultDataService.getMetricsByTests().
{
         if (testIds.isEmpty()) {
             return Collections.emptyMap();
         }
         // Get
         List<String> sessionIds = databaseService.getSessionIdsByTaskIds(new HashSet<Long>(testIds));
         // Get all test results without matching
         SessionMatchingSetup sessionMatchingSetup = new SessionMatchingSetup(false, Collections.<SessionMatchingSetup.MatchBy>emptySet());
         RootNode rootNode = databaseService.getControlTreeForSessions(new HashSet<String>(sessionIds), sessionMatchingSetup);
         // Filter
         List<TestNode> summaryNodeTests = new ArrayList<TestNode>();
         List<TestDetailsNode> detailsNodeTests = new ArrayList<TestDetailsNode>();
         for (TestNode testNode : rootNode.getSummaryNode().getTests()) {
             Long testId = testNode.getTaskDataDto().getId();
             if (testIds.contains(testId)) {
                 summaryNodeTests.add(testNode);
             }
         }
         for (TestDetailsNode testDetailsNode : rootNode.getDetailsNode().getTests()) {
             Long testId = testDetailsNode.getTaskDataDto().getId();
             if (testIds.contains(testId)) {
                 detailsNodeTests.add(testDetailsNode);
             }
         }
         // Join
         Map<Long, Set<MetricNameDto>> metrics = new HashMap<Long, Set<MetricNameDto>>();
         Set<String> metricsWithSummary = new HashSet<String>();
         Set<String> metricsWithPlots = new HashSet<String>();
         for (TestNode testNode : summaryNodeTests) {
             Long testId = testNode.getTaskDataDto().getId();
             if (!metrics.containsKey(testId)) {
                 metrics.put(testId, new HashSet<MetricNameDto>());
             }
             for (MetricNode metricNode : testNode.getMetrics()) {
                 for (MetricNameDto metricNameDto : metricNode.getMetricNameDtoList()) {
                     metrics.get(testId).add(metricNameDto);
                     metricsWithSummary.add(metricNameDto.getMetricName());
                 }
             }
         }
         for (TestDetailsNode testDetailsNode : detailsNodeTests) {
             Long testId = testDetailsNode.getTaskDataDto().getId();
             if (!metrics.containsKey(testId)) {
                 metrics.put(testId, new HashSet<MetricNameDto>());
             }
             for (MetricNode metricNode : testDetailsNode.getMetrics()) {
                 for (MetricNameDto metricNameDto : metricNode.getMetricNameDtoList()) {
                     metrics.get(testId).add(metricNameDto);
                     metricsWithPlots.add(metricNameDto.getMetricName());
                 }
             }
         }
         // Convert
         Map<Long, Set<MetricEntity>> result = new HashMap<Long, Set<MetricEntity>>();
         for (Long key : metrics.keySet()) {
             result.put(key, new HashSet<MetricEntity>());
             for (MetricNameDto metricNameDto : metrics.get(key)) {
                 MetricEntity metricEntity = new MetricEntity();
                 metricEntity.setMetricNameDto(metricNameDto);
                 if (metricsWithSummary.contains(metricNameDto.getMetricName())) {
                     metricEntity.setSummaryAvailable(true);
                 }
                 if (metricsWithPlots.contains(metricNameDto.getMetricName())) {
                     metricEntity.setPlotAvailable(true);
                 }
                 result.get(key).add(metricEntity);
             }
         }
         return result;
     }