Jagger: com.griddynamics.jagger.engine.e1.services.DefaultDataService.getTestsWithName
Map<String, Set<TestEntity> > com.griddynamics.jagger.engine.e1.services.DefaultDataService.getTestsWithName (Collection< String > sessionIds, String testName, SessionMatchingSetup sessionMatchingSetup)
Definition at line 135 of file DefaultDataService.java.
References com.griddynamics.jagger.engine.e1.services.data.service.TestEntity.setClockValue(), com.griddynamics.jagger.engine.e1.services.data.service.TestEntity.setDecision(), com.griddynamics.jagger.engine.e1.services.data.service.TestEntity.setDescription(), com.griddynamics.jagger.engine.e1.services.data.service.TestEntity.setId(), com.griddynamics.jagger.engine.e1.services.data.service.TestEntity.setLoad(), com.griddynamics.jagger.engine.e1.services.data.service.TestEntity.setName(), com.griddynamics.jagger.engine.e1.services.data.service.TestEntity.setStartDate(), com.griddynamics.jagger.engine.e1.services.data.service.TestEntity.setTaskDataDto(), com.griddynamics.jagger.engine.e1.services.data.service.TestEntity.setTerminationStrategy(), com.griddynamics.jagger.engine.e1.services.data.service.TestEntity.setTestExecutionStatus(), and com.griddynamics.jagger.engine.e1.services.data.service.TestEntity.setTestGroupIndex().
Referenced by com.griddynamics.jagger.engine.e1.services.DefaultDataService.getTests(), and com.griddynamics.jagger.engine.e1.services.DefaultDataService.getTestsByName().
{
         if (sessionIds.isEmpty()) {
             return Collections.emptyMap();
         }
         // basic
         List<TaskDataDto> taskDataDtoList = databaseService.getTaskDataForSessions(new HashSet<String>(sessionIds), sessionMatchingSetup);
         // info
         Map<TaskDataDto, Map<String, TestInfoDto>> testInfoMap = databaseService.getTestInfoByTaskDataDto(taskDataDtoList);
         // decision
         Set<Long> ids = new HashSet<Long>();
         for (TaskDataDto taskDataDto : taskDataDtoList) {
             ids.addAll(taskDataDto.getIds());
         }
         Map<Long, TaskDecisionDto> idToDecisionPerTest = new HashMap<Long, TaskDecisionDto>();
         for (TaskDecisionDto taskDecisionDto : databaseService.getDecisionsPerTask(ids)) {
             idToDecisionPerTest.put(taskDecisionDto.getId(), taskDecisionDto);
         }
         Map<String, Set<TestEntity>> result = new HashMap<String, Set<TestEntity>>();
         for (TaskDataDto taskDataDto : taskDataDtoList) {
             for (Map.Entry<Long, String> entry : taskDataDto.getIdToSessionId().entrySet()) {
                 if (((testName != null) && (testName.equals(taskDataDto.getTaskName()))) ||
                         (testName == null)) {
                     Long testId = entry.getKey();
                     String sessionId = entry.getValue();
                     TestEntity testEntity = new TestEntity();
                     testEntity.setId(testId);
                     testEntity.setDescription(taskDataDto.getDescription());
                     testEntity.setName(taskDataDto.getTaskName());
                     testEntity.setTaskDataDto(taskDataDto);
                     if (testInfoMap.containsKey(taskDataDto)) {
                         TestInfoDto testInfoDto = testInfoMap.get(taskDataDto).entrySet().iterator().next().getValue();
                         testEntity.setLoad(testInfoDto.getClock());
                         testEntity.setClockValue(testInfoDto.getClockValue());
                         testEntity.setTerminationStrategy(testInfoDto.getTermination());
                         testEntity.setStartDate(testInfoDto.getStartTime());
                         testEntity.setTestGroupIndex(testInfoDto.getNumber());
                         testEntity.setTestExecutionStatus(testInfoDto.getStatus());
                     }
                     if (idToDecisionPerTest.containsKey(testId)) {
                         testEntity.setDecision(idToDecisionPerTest.get(testId).getDecision());
                     }
                     if (result.containsKey(sessionId)) {
                         result.get(sessionId).add(testEntity);
                     } else {
                         Set<TestEntity> testEntitySet = new HashSet<TestEntity>();
                         testEntitySet.add(testEntity);
                         result.put(sessionId, testEntitySet);
                     }
                 }
             }
         }
         // add empty results when not found
         for (String sessionId : sessionIds) {
             if (!result.containsKey(sessionId)) {
                 result.put(sessionId, Collections.<TestEntity>emptySet());
             }
         }
         return result;
     }