Jagger: com.griddynamics.jagger.user.test.configurations.limits.auxiliary.LowWarnThresh.of
static LowWarnThresh com.griddynamics.jagger.user.test.configurations.limits.auxiliary.LowWarnThresh.of (Double value) static
Definition at line 13 of file LowWarnThresh.java.
Referenced by JLoadScenarioProvider.exampleJaggerLoadScenario(), com.griddynamics.jagger.user.test.configurations.limits.JLimit.Builder.withOnlyErrors(), and com.griddynamics.jagger.user.test.configurations.limits.JLimit.Builder.withOnlyUpperThresholds().
{
         return new LowWarnThresh(value);
     }