Jagger: com.griddynamics.jagger.invoker.scenario.JHttpUserScenarioInvocationListener.provide
InvocationListener com.griddynamics.jagger.invoker.scenario.JHttpUserScenarioInvocationListener.provide ()
Definition at line 85 of file JHttpUserScenarioInvocationListener.java.
References com.griddynamics.jagger.invoker.scenario.JHttpUserScenarioInvocationResult.getScenarioDisplayName(), com.griddynamics.jagger.invoker.scenario.JHttpUserScenarioInvocationResult.getScenarioId(), com.griddynamics.jagger.invoker.scenario.JHttpUserScenarioInvocationResult.getStepInvocationResults(), com.griddynamics.jagger.invoker.scenario.JHttpUserScenarioInvocationResult.getSucceeded(), and com.griddynamics.jagger.engine.e1.collector.MetricDescription.plotData.
{
         return new InvocationListener() {
             @Override
             public void onStart(InvocationInfo invocationInfo) { }
             @Override
             public void onSuccess(InvocationInfo invocationInfo) {
                 if (invocationInfo.getResult() != null) {
                     JHttpUserScenarioInvocationResult invocationResult = ((JHttpUserScenarioInvocationResult) invocationInfo.getResult());
                     List<JHttpUserScenarioStepInvocationResult> stepInvocationResults = invocationResult.getStepInvocationResults();
                     String scenarioId = generateScenarioId(invocationResult.getScenarioId());
                     // Create & save scenario metrics
                     if (!createdMetrics.contains(scenarioId)) {
                         createdMetrics.add(scenarioId);
                         createScenarioMetricDescriptions(scenarioId, invocationResult.getScenarioDisplayName());
                     }
                     getMetricService().saveValue(generateMetricId(scenarioId, ITERATION_SAMPLES_ID), 1);
                     getMetricService().saveValue(generateMetricId(scenarioId, LATENCY_ID),
                             invocationInfo.getDuration() / 1000.0); // ms -> s
                     getMetricService().saveValue(generateMetricId(scenarioId, SUCCESS_RATE_ID), invocationResult.getSucceeded() ? 1 : 0);
                     // Create & save step metrics
                     Integer stepIndex = 1; // index 0 for scenario (not steps) metrics
                     for (JHttpUserScenarioStepInvocationResult stepResult : stepInvocationResults) {
                         String scenarioStepId = generateScenarioStepId(invocationResult.getScenarioId(), stepResult.getStepId(), stepIndex);
                         if (!createdMetrics.contains(scenarioStepId)) {
                             createdMetrics.add(scenarioStepId);
                             createScenarioStepMetricDescriptions(scenarioStepId,String.format("%02d. %s ", stepIndex, stepResult.getStepDisplayName()));
                         }
                         getMetricService().saveValue(generateMetricId(scenarioStepId, LATENCY_ID),
                                 stepResult.getLatency().doubleValue() / 1000); // ms -> s
                         getMetricService().saveValue(generateMetricId(scenarioStepId, SUCCESS_RATE_ID), stepResult.getSucceeded() ? 1 : 0);
                         getMetricService().saveValue(generateMetricId(scenarioStepId, ITERATION_SAMPLES_ID), 1);
                         stepIndex++;
                     }
                 }
             }
             private void createScenarioMetricDescriptions(String scenarioId, String scenarioDisplayName) {
                 getMetricService().createMetric(
                         new MetricDescription(generateMetricId(scenarioId, ITERATION_SAMPLES_ID)).
                                 displayName(generateMetricDisplayName(scenarioDisplayName, ITERATIONS_SAMPLES)).
                                 addAggregator(SUM_AGGREGATOR));
                 getMetricService().createMetric(
                         new MetricDescription(generateMetricId(scenarioId, LATENCY_ID)).
                                 displayName(generateMetricDisplayName(scenarioDisplayName, LATENCY_SEC)).
                                 addAggregator(AVG_AGGREGATOR));
                 getMetricService().createMetric(
                         new MetricDescription(generateMetricId(scenarioId, SUCCESS_RATE_ID)).
                                 displayName(generateMetricDisplayName(scenarioDisplayName, SUCCESS_RATE)).
                                 plotData(true).
                                 addAggregator(SUCCESS_AGGREGATOR).
                                 addAggregator(FAILS_AGGREGATOR));
             }
             private void createScenarioStepMetricDescriptions(String scenarioStepId, String scenarioStepDisplayName) {
                 MetricDescription metricDescription =
                         new MetricDescription(generateMetricId(scenarioStepId,LATENCY_ID)).
                                 displayName(generateMetricDisplayName(scenarioStepDisplayName,LATENCY_SEC))
                                 .plotData(true);
                 if (latencyAggregatorProviders.isEmpty())
                     latencyAggregatorProviders.addAll(newHashSet(MAX_AGGREGATOR, MIN_AGGREGATOR, STD_DEV_AGGREGATOR, AVG_AGGREGATOR));
                 latencyAggregatorProviders.forEach(metricDescription::addAggregator);
                 getMetricService().createMetric(metricDescription);
                 getMetricService().createMetric(
                         new MetricDescription(generateMetricId(scenarioStepId, ITERATION_SAMPLES_ID)).
                                 displayName(generateMetricDisplayName(scenarioStepDisplayName, ITERATIONS_SAMPLES)).
                                 addAggregator(SUM_AGGREGATOR));
                 getMetricService().createMetric(
                         new MetricDescription(generateMetricId(scenarioStepId, SUCCESS_RATE_ID)).
                                 displayName(generateMetricDisplayName(scenarioStepDisplayName, SUCCESS_RATE)).
                                 plotData(true).
                                 addAggregator(SUCCESS_AGGREGATOR).
                                 addAggregator(FAILS_AGGREGATOR));
             }
             @Override
             public void onFail(InvocationInfo invocationInfo, InvocationException e) {
                 //TODO: JFG-1122
             }
             @Override
             public void onError(InvocationInfo invocationInfo, Throwable error) {
                 //TODO: JFG-1122
             }
         };
     }