Jagger: ExampleJLoadScenarioProvider.exampleJaggerLoadScenario
JLoadScenario ExampleJLoadScenarioProvider.exampleJaggerLoadScenario ()
Definition at line 55 of file ExampleJLoadScenarioProvider.java.
References com.griddynamics.jagger.user.test.configurations.load.JLoadProfileRps.Builder.build(), com.griddynamics.jagger.user.test.configurations.JLoadTest.Builder.build(), com.griddynamics.jagger.user.test.configurations.limits.JLimitVsBaseline.builder(), com.griddynamics.jagger.user.test.configurations.limits.JLimitVsRefValue.builder(), com.griddynamics.jagger.user.test.configurations.JParallelTestsGroup.builder(), com.griddynamics.jagger.user.test.configurations.JLoadScenario.builder(), com.griddynamics.jagger.user.test.configurations.load.JLoadProfileRps.builder(), com.griddynamics.jagger.user.test.configurations.JLoadTest.builder(), com.griddynamics.jagger.user.test.configurations.JTestDefinition.builder(), ExampleCustomHttpInvokerProvider.nonVerbose(), com.griddynamics.jagger.user.test.configurations.limits.auxiliary.LowWarnThresh.of(), com.griddynamics.jagger.user.test.configurations.limits.auxiliary.LowErrThresh.of(), com.griddynamics.jagger.user.test.configurations.limits.auxiliary.UpErrThresh.of(), com.griddynamics.jagger.user.test.configurations.limits.auxiliary.UpWarnThresh.of(), com.griddynamics.jagger.user.test.configurations.limits.auxiliary.RefValue.of(), com.griddynamics.jagger.user.test.configurations.termination.auxiliary.IterationsNumber.of(), com.griddynamics.jagger.user.test.configurations.termination.auxiliary.MaxDurationInSeconds.of(), com.griddynamics.jagger.user.test.configurations.auxiliary.Id.of(), com.griddynamics.jagger.user.test.configurations.load.auxiliary.RequestsPerSecond.of(), com.griddynamics.jagger.engine.e1.collector.DefaultResponseValidatorProvider.of(), com.griddynamics.jagger.user.test.configurations.termination.JTerminationCriteriaIterations.of(), com.griddynamics.jagger.user.test.configurations.limits.auxiliary.JMetricName.PERF_LATENCY_PERCENTILE(), com.griddynamics.jagger.user.test.configurations.limits.auxiliary.JMetricName.PERF_SUCCESS_RATE_OK, com.griddynamics.jagger.user.test.configurations.limits.auxiliary.JMetricName.PERF_THROUGHPUT, com.griddynamics.jagger.user.test.configurations.JTestDefinition.Builder.withInvoker(), com.griddynamics.jagger.user.test.configurations.limits.JLimit.Builder.withOnlyErrors(), and com.griddynamics.jagger.user.test.configurations.load.JLoadProfileRps.Builder.withWarmUpTimeInMilliseconds().
{
         // Example of using JaggerPropertiesProvider
         String testDefinitionComment = getTestPropertyValue("example.jagger.test.definition.comment");
         JTestDefinition jTestDefinition = JTestDefinition
                 .builder(Id.of("exampleJaggerTestDefinition"), new ExampleEndpointsProvider())
                 // optional
                 .withComment(testDefinitionComment)
                 .withInvoker(ExampleCustomHttpInvokerProvider.nonVerbose())
                 .withQueryProvider(new ExampleQueriesProvider())
                 .withLoadBalancer(new RoundRobinLoadBalancer())
                 .addValidator(new ExampleResponseValidatorProvider("we are always good"))
                 .addValidator(DefaultResponseValidatorProvider.of(NotNullResponseValidator.class))
                 .addListener(new NotNullInvocationListener())
                 .build();
         // Example of using JaggerPropertiesProvider
         Long iterationsNumber = Long.valueOf(getTestPropertyValue("example.jagger.load.scenario.termination.iterations"));
         Long maxDurationInSeconds = Long.valueOf(getTestPropertyValue("example.jagger.load.scenario.termination.max.duration.seconds"));
         JTerminationCriteria jTerminationCriteria = JTerminationCriteriaIterations
                 .of(IterationsNumber.of(iterationsNumber), MaxDurationInSeconds.of(maxDurationInSeconds));
         JLoadProfile jLoadProfileRps = JLoadProfileRps
                 .builder(RequestsPerSecond.of(10))
                 .withMaxLoadThreads(10)
                 .withWarmUpTimeInMilliseconds(10000)
                 .build();
         // For standard metrics use JMetricName.
         // JLimitVsRefValue is used to compare the results with the referenced value.
         JLimit successRateLimit = JLimitVsRefValue.builder(JMetricName.PERF_SUCCESS_RATE_OK, RefValue.of(1D))
                 // the threshold is relative.
                 .withOnlyWarnings(LowWarnThresh.of(0.99), UpWarnThresh.of(1.01))
                 .build();
         // For standard metrics use JMetricName.
         // JLimitVsBaseline is used to compare the results with the baseline.
         // Use 'chassis.engine.e1.reporting.session.comparison.baseline.session.id' to set baseline.
         JLimit throughputLimit = JLimitVsBaseline.builder(JMetricName.PERF_THROUGHPUT)
                 // the threshold is relative.
                 .withOnlyErrors(LowErrThresh.of(0.99), UpErrThresh.of(1.00001))
                 .build();
         // For standard metrics use JMetricName.
         // JMetricName.PERF_LATENCY_PERCENTILE is used to set limits for latency percentile metrics.
         JLimit latencyPercentileLimit = JLimitVsRefValue.builder(JMetricName.PERF_LATENCY_PERCENTILE(95D), RefValue.of(0.1D))
                 // the threshold is relative.
                 .withOnlyWarnings(LowWarnThresh.of(0.50), UpWarnThresh.of(1.5))
                 .build();
         JLoadTest jLoadTest = JLoadTest
                 .builder(Id.of("exampleJaggerLoadTest"), jTestDefinition, jLoadProfileRps, jTerminationCriteria)
                 .addListener(new CollectThreadsTestListener())
                 .withLimits(successRateLimit, throughputLimit, latencyPercentileLimit)
                 .build();
         JParallelTestsGroup jParallelTestsGroup = JParallelTestsGroup
                 .builder(Id.of("exampleJaggerParallelTestsGroup"), jLoadTest)
                 .addListener(new ExampleTestGroupListener())
                 .build();
         // For JLoadScenario which is supposed to be executed by Jagger its ID must be set to 'jagger.load.scenario.id.to.execute' property's value
         return JLoadScenario.builder(Id.of("exampleJaggerLoadScenario"), jParallelTestsGroup)
                 .addListener(new ExampleLoadScenarioListener())
                 .withLatencyPercentiles(Arrays.asList(10D, 25.5D, 42D, 95D))
                 .build();
     }