Jagger: com.griddynamics.jagger.invoker.scenario.JHttpScenarioGlobalContext.copy
JHttpScenarioGlobalContext com.griddynamics.jagger.invoker.scenario.JHttpScenarioGlobalContext.copy ()
Definition at line 22 of file JHttpScenarioGlobalContext.java.
References com.griddynamics.jagger.invoker.scenario.CopyUtil.copyOf(), com.griddynamics.jagger.invoker.v2.JHttpEndpoint.copyOf(), com.griddynamics.jagger.invoker.scenario.JHttpScenarioGlobalContext.withBasicAuth(), com.griddynamics.jagger.invoker.scenario.JHttpScenarioGlobalContext.withGlobalEndpoint(), and com.griddynamics.jagger.invoker.scenario.JHttpScenarioGlobalContext.withGlobalHeaders().
Referenced by com.griddynamics.jagger.invoker.scenario.JHttpUserScenarioInvoker.invoke().
{
         JHttpScenarioGlobalContext copy = new JHttpScenarioGlobalContext();
         return copy.withBasicAuth(this.userName, this.password)
                 .withGlobalEndpoint(JHttpEndpoint.copyOf(this.globalEndpoint))
                 .withGlobalHeaders(CopyUtil.copyOf(this.globalHeaders));
     }