// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raw_data_package.proto

package com.griddynamics.jagger.rawdatasender.protobuf;

public final class RawDataPackageProtos {
  private RawDataPackageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RawDataPackageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.RawDataPackage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>required string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>repeated .protobuf.TimeValue result = 2;</code>
     */
    java.util.List<com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue> 
        getResultList();
    /**
     * <code>repeated .protobuf.TimeValue result = 2;</code>
     */
    com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue getResult(int index);
    /**
     * <code>repeated .protobuf.TimeValue result = 2;</code>
     */
    int getResultCount();
    /**
     * <code>repeated .protobuf.TimeValue result = 2;</code>
     */
    java.util.List<? extends com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValueOrBuilder> 
        getResultOrBuilderList();
    /**
     * <code>repeated .protobuf.TimeValue result = 2;</code>
     */
    com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValueOrBuilder getResultOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code protobuf.RawDataPackage}
   */
  public  static final class RawDataPackage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.RawDataPackage)
      RawDataPackageOrBuilder {
    // Use RawDataPackage.newBuilder() to construct.
    private RawDataPackage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RawDataPackage() {
      id_ = "";
      result_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RawDataPackage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              id_ = bs;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                result_ = new java.util.ArrayList<com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue>();
                mutable_bitField0_ |= 0x00000002;
              }
              result_.add(
                  input.readMessage(com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          result_ = java.util.Collections.unmodifiableList(result_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.internal_static_protobuf_RawDataPackage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.internal_static_protobuf_RawDataPackage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.RawDataPackage.class, com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.RawDataPackage.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>required string id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESULT_FIELD_NUMBER = 2;
    private java.util.List<com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue> result_;
    /**
     * <code>repeated .protobuf.TimeValue result = 2;</code>
     */
    public java.util.List<com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue> getResultList() {
      return result_;
    }
    /**
     * <code>repeated .protobuf.TimeValue result = 2;</code>
     */
    public java.util.List<? extends com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValueOrBuilder> 
        getResultOrBuilderList() {
      return result_;
    }
    /**
     * <code>repeated .protobuf.TimeValue result = 2;</code>
     */
    public int getResultCount() {
      return result_.size();
    }
    /**
     * <code>repeated .protobuf.TimeValue result = 2;</code>
     */
    public com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue getResult(int index) {
      return result_.get(index);
    }
    /**
     * <code>repeated .protobuf.TimeValue result = 2;</code>
     */
    public com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValueOrBuilder getResultOrBuilder(
        int index) {
      return result_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getResultCount(); i++) {
        if (!getResult(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      for (int i = 0; i < result_.size(); i++) {
        output.writeMessage(2, result_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      for (int i = 0; i < result_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, result_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.RawDataPackage)) {
        return super.equals(obj);
      }
      com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.RawDataPackage other = (com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.RawDataPackage) obj;

      boolean result = true;
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && getId()
            .equals(other.getId());
      }
      result = result && getResultList()
          .equals(other.getResultList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId().hashCode();
      }
      if (getResultCount() > 0) {
        hash = (37 * hash) + RESULT_FIELD_NUMBER;
        hash = (53 * hash) + getResultList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.RawDataPackage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.RawDataPackage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.RawDataPackage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.RawDataPackage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.RawDataPackage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.RawDataPackage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.RawDataPackage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.RawDataPackage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.RawDataPackage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.RawDataPackage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.RawDataPackage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.RawDataPackage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.RawDataPackage)
        com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.RawDataPackageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.internal_static_protobuf_RawDataPackage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.internal_static_protobuf_RawDataPackage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.RawDataPackage.class, com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.RawDataPackage.Builder.class);
      }

      // Construct using com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.RawDataPackage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getResultFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (resultBuilder_ == null) {
          result_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          resultBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.internal_static_protobuf_RawDataPackage_descriptor;
      }

      public com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.RawDataPackage getDefaultInstanceForType() {
        return com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.RawDataPackage.getDefaultInstance();
      }

      public com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.RawDataPackage build() {
        com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.RawDataPackage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.RawDataPackage buildPartial() {
        com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.RawDataPackage result = new com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.RawDataPackage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (resultBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            result_ = java.util.Collections.unmodifiableList(result_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.result_ = result_;
        } else {
          result.result_ = resultBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.RawDataPackage) {
          return mergeFrom((com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.RawDataPackage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.RawDataPackage other) {
        if (other == com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.RawDataPackage.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (resultBuilder_ == null) {
          if (!other.result_.isEmpty()) {
            if (result_.isEmpty()) {
              result_ = other.result_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureResultIsMutable();
              result_.addAll(other.result_);
            }
            onChanged();
          }
        } else {
          if (!other.result_.isEmpty()) {
            if (resultBuilder_.isEmpty()) {
              resultBuilder_.dispose();
              resultBuilder_ = null;
              result_ = other.result_;
              bitField0_ = (bitField0_ & ~0x00000002);
              resultBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getResultFieldBuilder() : null;
            } else {
              resultBuilder_.addAllMessages(other.result_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        for (int i = 0; i < getResultCount(); i++) {
          if (!getResult(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.RawDataPackage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.RawDataPackage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>required string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue> result_ =
        java.util.Collections.emptyList();
      private void ensureResultIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          result_ = new java.util.ArrayList<com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue>(result_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue, com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue.Builder, com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValueOrBuilder> resultBuilder_;

      /**
       * <code>repeated .protobuf.TimeValue result = 2;</code>
       */
      public java.util.List<com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue> getResultList() {
        if (resultBuilder_ == null) {
          return java.util.Collections.unmodifiableList(result_);
        } else {
          return resultBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protobuf.TimeValue result = 2;</code>
       */
      public int getResultCount() {
        if (resultBuilder_ == null) {
          return result_.size();
        } else {
          return resultBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protobuf.TimeValue result = 2;</code>
       */
      public com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue getResult(int index) {
        if (resultBuilder_ == null) {
          return result_.get(index);
        } else {
          return resultBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protobuf.TimeValue result = 2;</code>
       */
      public Builder setResult(
          int index, com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue value) {
        if (resultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultIsMutable();
          result_.set(index, value);
          onChanged();
        } else {
          resultBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.TimeValue result = 2;</code>
       */
      public Builder setResult(
          int index, com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue.Builder builderForValue) {
        if (resultBuilder_ == null) {
          ensureResultIsMutable();
          result_.set(index, builderForValue.build());
          onChanged();
        } else {
          resultBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.TimeValue result = 2;</code>
       */
      public Builder addResult(com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue value) {
        if (resultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultIsMutable();
          result_.add(value);
          onChanged();
        } else {
          resultBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.TimeValue result = 2;</code>
       */
      public Builder addResult(
          int index, com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue value) {
        if (resultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultIsMutable();
          result_.add(index, value);
          onChanged();
        } else {
          resultBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.TimeValue result = 2;</code>
       */
      public Builder addResult(
          com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue.Builder builderForValue) {
        if (resultBuilder_ == null) {
          ensureResultIsMutable();
          result_.add(builderForValue.build());
          onChanged();
        } else {
          resultBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.TimeValue result = 2;</code>
       */
      public Builder addResult(
          int index, com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue.Builder builderForValue) {
        if (resultBuilder_ == null) {
          ensureResultIsMutable();
          result_.add(index, builderForValue.build());
          onChanged();
        } else {
          resultBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.TimeValue result = 2;</code>
       */
      public Builder addAllResult(
          java.lang.Iterable<? extends com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue> values) {
        if (resultBuilder_ == null) {
          ensureResultIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, result_);
          onChanged();
        } else {
          resultBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.TimeValue result = 2;</code>
       */
      public Builder clearResult() {
        if (resultBuilder_ == null) {
          result_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          resultBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.TimeValue result = 2;</code>
       */
      public Builder removeResult(int index) {
        if (resultBuilder_ == null) {
          ensureResultIsMutable();
          result_.remove(index);
          onChanged();
        } else {
          resultBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.TimeValue result = 2;</code>
       */
      public com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue.Builder getResultBuilder(
          int index) {
        return getResultFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protobuf.TimeValue result = 2;</code>
       */
      public com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValueOrBuilder getResultOrBuilder(
          int index) {
        if (resultBuilder_ == null) {
          return result_.get(index);  } else {
          return resultBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protobuf.TimeValue result = 2;</code>
       */
      public java.util.List<? extends com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValueOrBuilder> 
           getResultOrBuilderList() {
        if (resultBuilder_ != null) {
          return resultBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(result_);
        }
      }
      /**
       * <code>repeated .protobuf.TimeValue result = 2;</code>
       */
      public com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue.Builder addResultBuilder() {
        return getResultFieldBuilder().addBuilder(
            com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.TimeValue result = 2;</code>
       */
      public com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue.Builder addResultBuilder(
          int index) {
        return getResultFieldBuilder().addBuilder(
            index, com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.TimeValue result = 2;</code>
       */
      public java.util.List<com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue.Builder> 
           getResultBuilderList() {
        return getResultFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue, com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue.Builder, com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValueOrBuilder> 
          getResultFieldBuilder() {
        if (resultBuilder_ == null) {
          resultBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue, com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue.Builder, com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValueOrBuilder>(
                  result_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          result_ = null;
        }
        return resultBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.RawDataPackage)
    }

    // @@protoc_insertion_point(class_scope:protobuf.RawDataPackage)
    private static final com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.RawDataPackage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.RawDataPackage();
    }

    public static com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.RawDataPackage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<RawDataPackage>
        PARSER = new com.google.protobuf.AbstractParser<RawDataPackage>() {
      public RawDataPackage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RawDataPackage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RawDataPackage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RawDataPackage> getParserForType() {
      return PARSER;
    }

    public com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.RawDataPackage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TimeValueOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.TimeValue)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 time = 1;</code>
     */
    boolean hasTime();
    /**
     * <code>required int64 time = 1;</code>
     */
    long getTime();

    /**
     * <code>optional double value = 2;</code>
     */
    boolean hasValue();
    /**
     * <code>optional double value = 2;</code>
     */
    double getValue();
  }
  /**
   * Protobuf type {@code protobuf.TimeValue}
   */
  public  static final class TimeValue extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.TimeValue)
      TimeValueOrBuilder {
    // Use TimeValue.newBuilder() to construct.
    private TimeValue(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TimeValue() {
      time_ = 0L;
      value_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TimeValue(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              time_ = input.readInt64();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              value_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.internal_static_protobuf_TimeValue_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.internal_static_protobuf_TimeValue_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue.class, com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue.Builder.class);
    }

    private int bitField0_;
    public static final int TIME_FIELD_NUMBER = 1;
    private long time_;
    /**
     * <code>required int64 time = 1;</code>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 time = 1;</code>
     */
    public long getTime() {
      return time_;
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private double value_;
    /**
     * <code>optional double value = 2;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional double value = 2;</code>
     */
    public double getValue() {
      return value_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, time_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, value_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, time_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, value_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue)) {
        return super.equals(obj);
      }
      com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue other = (com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue) obj;

      boolean result = true;
      result = result && (hasTime() == other.hasTime());
      if (hasTime()) {
        result = result && (getTime()
            == other.getTime());
      }
      result = result && (hasValue() == other.hasValue());
      if (hasValue()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getValue())
            == java.lang.Double.doubleToLongBits(
                other.getValue()));
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasTime()) {
        hash = (37 * hash) + TIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTime());
      }
      if (hasValue()) {
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getValue()));
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.TimeValue}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.TimeValue)
        com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValueOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.internal_static_protobuf_TimeValue_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.internal_static_protobuf_TimeValue_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue.class, com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue.Builder.class);
      }

      // Construct using com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        time_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.internal_static_protobuf_TimeValue_descriptor;
      }

      public com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue getDefaultInstanceForType() {
        return com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue.getDefaultInstance();
      }

      public com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue build() {
        com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue buildPartial() {
        com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue result = new com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.time_ = time_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue) {
          return mergeFrom((com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue other) {
        if (other == com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue.getDefaultInstance()) return this;
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTime()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long time_ ;
      /**
       * <code>required int64 time = 1;</code>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 time = 1;</code>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <code>required int64 time = 1;</code>
       */
      public Builder setTime(long value) {
        bitField0_ |= 0x00000001;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 time = 1;</code>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        time_ = 0L;
        onChanged();
        return this;
      }

      private double value_ ;
      /**
       * <code>optional double value = 2;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional double value = 2;</code>
       */
      public double getValue() {
        return value_;
      }
      /**
       * <code>optional double value = 2;</code>
       */
      public Builder setValue(double value) {
        bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double value = 2;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = 0D;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.TimeValue)
    }

    // @@protoc_insertion_point(class_scope:protobuf.TimeValue)
    private static final com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue();
    }

    public static com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<TimeValue>
        PARSER = new com.google.protobuf.AbstractParser<TimeValue>() {
      public TimeValue parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TimeValue(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TimeValue> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TimeValue> getParserForType() {
      return PARSER;
    }

    public com.griddynamics.jagger.rawdatasender.protobuf.RawDataPackageProtos.TimeValue getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_RawDataPackage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_RawDataPackage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_TimeValue_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_TimeValue_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026raw_data_package.proto\022\010protobuf\"A\n\016Ra" +
      "wDataPackage\022\n\n\002id\030\001 \002(\t\022#\n\006result\030\002 \003(\013" +
      "2\023.protobuf.TimeValue\"(\n\tTimeValue\022\014\n\004ti" +
      "me\030\001 \002(\003\022\r\n\005value\030\002 \001(\001BF\n.com.griddynam" +
      "ics.jagger.rawdatasender.protobufB\024RawDa" +
      "taPackageProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protobuf_RawDataPackage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_RawDataPackage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_RawDataPackage_descriptor,
        new java.lang.String[] { "Id", "Result", });
    internal_static_protobuf_TimeValue_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protobuf_TimeValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_TimeValue_descriptor,
        new java.lang.String[] { "Time", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
