#
# Docker Compose configuration file for existing test results DB.
#

version: "2"
services:
  # Container with mysql base for jaas
  jaas-mysql:
    image: mysql:5.7
    container_name: jaas-mysql
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: jaggeruser
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: jaasdb

  jagger-web-client:
    image: griddynamics/jagger-web-client:${project.version}
    container_name: jagger-web-client
    ports:
      - 8087:80
    environment:
      TZ: Europe/Moscow
      JWC_HTTP_PORT: 80
      JWC_JDBC_DRIVER: com.mysql.jdbc.Driver
      # Specify here the existing results database
      JWC_JDBC_URL: jdbc:mysql://<hostname>:<port>/<base_name>
      JWC_JDBC_USER: <username>
      JWC_JDBC_PASS: <password>
      MYSQL_PORT: 3306
      MYSQL_HOST: <hostname>

  jagger-jaas:
    image: griddynamics/jagger-jaas:${project.version}
    container_name: jagger-jaas
    ports:
      - 8088:8080
    depends_on:
      - jaas-mysql
    environment:
      JAAS_HTTP_PORT: 8080
      JAAS_DB_URL: jdbc:mysql://jaas-mysql:3306/jaasdb
      JAAS_DB_DRIVER: com.mysql.jdbc.Driver
      JAAS_DB_USER: jaggeruser
      JAAS_DB_PASS: password
      JAAS_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
      MYSQL_PORT: 3306
      MYSQL_HOST: jaas-mysql
      # Specify here the existing results database
      JAGGER_DB_DEFAULT_URL: jdbc:mysql://<hostname>:<port>/<base_name>
      JAGGER_DB_DEFAULT_DESC: default_db
      JAGGER_DB_DEFAULT_USER: <username>
      JAGGER_DB_DEFAULT_PASSWORD: <password>
      JAGGER_DB_DEFAULT_DRIVER: com.mysql.jdbc.Driver
      JAGGER_DB_DEFAULT_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
