version: "2"
services:
  # Container with mysql base for jaas
  jaas-mysql:
    image: mysql:5.7
    container_name: jaas-mysql
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: jaggeruser
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: jaasdb

  jagger-web-client:
    image: griddynamics/jagger-web-client:snapshot
    container_name: jagger-web-client
    ports:
      - 8087:80
    environment:
      TZ: Europe/Moscow
      JWC_HTTP_PORT: 80
      JWC_JDBC_DRIVER: com.mysql.jdbc.Driver
      JWC_JDBC_URL: jdbc:mysql://jagger-ci1.vm.griddynamics.net:3306/jaggerdb
      JWC_JDBC_USER: jagger
      JWC_JDBC_PASS: rocks

  jagger-jaas:
    image: griddynamics/jagger-jaas:snapshot
    container_name: jagger-jaas
    ports:
      - 8088:8080
    depends_on:
      - jaas-mysql
    environment:
      JAAS_HTTP_PORT: 8080
      JAAS_DB_URL: jdbc:mysql://jaas-mysql:3306/jaasdb
      JAAS_DB_DRIVER: com.mysql.jdbc.Driver
      JAAS_DB_USER: jaggeruser
      JAAS_DB_PASS: password
      JAAS_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
      # These parameters are optional, but you can avoid some issues if they are set (watch JFG-947).
      JAGGER_DB_DEFAULT_URL: jdbc:mysql://jagger-ci1.vm.griddynamics.net:3306/jaggerdb
      JAGGER_DB_DEFAULT_DESC: default_db
      JAGGER_DB_DEFAULT_USER: jagger
      JAGGER_DB_DEFAULT_PASSWORD: rocks
      JAGGER_DB_DEFAULT_DRIVER: com.mysql.jdbc.Driver
      JAGGER_DB_DEFAULT_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
