version: "2"
services:
  jagger-mysql:
    image: mysql:5.7
    container_name: jagger-mysql
    # Expose ports. Either specify both ports (HOST:CONTAINER), or just the
    # container port (a random host port will be chosen).
    ports:
      - 3306:3306
    # Set mysql environments
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: jaggeruser
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: jaggerdb  
    # Copy mysql config to the container
    volumes:
      - ./files/my.cnf:/etc/mysql/conf.d/my.cnf

  jagger-web-client:
    image: griddynamics/jagger-web-client:shapshot
    container_name: jagger-web-client
    ports:
      - 8080:80
    # Wait when jagger-mysql container started 
    depends_on:
      - jagger-mysql
    environment:
      TZ: Europe/Moscow
      JWC_HTTP_PORT: 80
      JWC_JDBC_DRIVER: com.mysql.jdbc.Driver
      JWC_JDBC_URL: jdbc:mysql://jagger-mysql:3306/jaggerdb
      JWC_JDBC_USER: jaggeruser
      JWC_JDBC_PASS: password
    # Link to containers in another service.
    links:
      - jagger-mysql
